### ISSUE TITLE
Investigate robot out of capsules

### ISSUE THREAD

**Issue by JakobThumm** [manuelvogel12/sara-shield#5]
We saw occasions where the capsules did not encapsulate all robot link entirely.

**Comment by manuelvogel12** [comment]
I found the problem source: 
This is caused by simulating gravity. 
This is how the capsules look in position `[2.5, 1.5, 0.0, 0.0, 0.0, 0.0]` with simulating gravity:
![image](https://github.com/manuelvogel12/sara-shield/assets/120781514/dca25f25-4fa8-4cac-aec9-0aa199c89b53)

And by disabling the gravity simulation in gazebo, by clicking the robot, then select L_X_E on the left side panel, and disabling the gravity checkbox (for every Link L_1_E to L_6_E), this problem can be avoided:

This is what it looks like after disabling gravity.  The arm is now fully encapsulated:
![image](https://github.com/manuelvogel12/sara-shield/assets/120781514/ab542256-18c7-4744-878c-dca5c7af7fa7)

So the problem is not caused by the capsule generation or sara-shield, but by the robot having different joint positions then specified

**Comment by JakobThumm** [comment]
Great find!
Ah, then this is a problem of the joint impedance control. We should ask them to adjust the gravity compensation.

**Comment by JakobThumm** [comment]
https://github.com/ADVRHumanoids/concert_description/issues/26
Continuation of this issue with IIT :)
